import type { Metadata } from "next";
//import { Inter } from "next/font/google";
import Provider from "@/Components/security/Provider";
import "@/styles/Home.css";
import "@/styles/globals.css";
import "@/styles/Prices.css";

//const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home Page | Eezydata",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={'dark:bg-corduroy-950'}> {/*grid grid-flow-row grid-cols-1 w-screen h-screen justify-center items-center inter.className}> */}
        <center>
          <Provider>
            {children}
          </Provider>
        </center>
      </body>
      
    </html>
  );
}
